version: 2
updates:
  - package-ecosystem: npm
    directory: /
    groups:
      babel:
        patterns:
          - '@babel/*'
          - 'babel-*'

      eslint-prettier:
        patterns:
          - 'prettier'
          - 'eslint'
          - 'eslint-*'
          - '@eslint/*'

      jest:
        patterns:
          - '@swc/jest'
          - 'jest'
          - 'jest-*'
          - 'supertest'

      playwright:
        patterns:
          - '@playwright/*'

      react:
        patterns:
          - 'react'
          - 'react-dom'
          - 'react-router'
          - 'react-router-dom'

      react-dnd:
        patterns:
          - 'react-dnd'
          - 'react-dnd-*'

      redux:
        patterns:
          - '@reduxjs/toolkit'
          - 'react-redux'

      richtext-editor:
        patterns:
          - 'markdown-it'
          - 'markdown-it-*'

      storybook:
        patterns:
          - 'storybook'
          - '@storybook/*'
          - '@storybook/addon-*'

      swc:
        patterns:
          - '@swc/*'
        exclude-patterns:
          - '@swc/jest'

      testing-library:
        patterns:
          - '@testing-library/*'

      typescript:
        patterns:
          - 'typescript'
          - 'ts-jest'
          - '@typescript-eslint/*'

      webpack:
        patterns:
          - 'webpack'
          - 'webpack-cli'
          - 'webpack-dev-server'
          - 'html-webpack-plugin'
          - 'webpack-bundle-analyzer'

    commit-message:
      prefix: 'chore'
      include: 'scope'
    schedule:
      interval: weekly
      day: sunday
      time: '22:00'
    open-pull-requests-limit: 5
    versioning-strategy: increase
    ignore:
      # Only allow patch as minor babel versions need to be upgraded all together
      - dependency-name: '@babel/*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'

    labels:
      - 'source: dependencies'
      - 'pr: chore'

  - package-ecosystem: github-actions
    open-pull-requests-limit: 5
    directory: /
    commit-message:
      prefix: 'chore'
      include: 'scope'
    schedule:
      interval: weekly
      day: sunday
      time: '22:00'
    labels:
      - 'source: dependencies'
      - 'pr: chore'
